name: "File existence check"

on: [push]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        # https://github.com/andstor/file-existence-action
        uses: andstor/file-existence-action@v1
        with:
          files: "LICENSE"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!
